"""empty message

Revision ID: 5c8d7a955be2
Revises: c2c74e3666d4
Create Date: 2022-08-25 16:26:28.034765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8d7a955be2'
down_revision = 'c2c74e3666d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('MPH',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Athletic_track',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Football_field',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Hockey_field',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('swimming_pool',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('others',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('others',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('swimming_pool',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Hockey_field',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Football_field',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Athletic_track',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('MPH',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
