"""empty message

Revision ID: 5d17ade6eaa5
Revises: 
Create Date: 2022-08-23 10:33:00.461652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d17ade6eaa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
