"""empty message

Revision ID: 6dad9ce5e35e
Revises: d92dc3e9c250
Create Date: 2022-08-25 16:35:25.714905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dad9ce5e35e'
down_revision = 'd92dc3e9c250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('serialnumber', sa.Integer(), nullable=False),
    sa.Column('state_or_ut', sa.String(), nullable=False),
    sa.Column('SAI_projects', sa.String(), nullable=False),
    sa.Column('other_projects', sa.String(), nullable=False),
    sa.Column('Amountsanctioned', sa.Integer(), nullable=False),
    sa.Column('Amountreleased', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('serialnumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funds')
    # ### end Alembic commands ###
