"""empty message

Revision ID: bd0a9b048386
Revises: e69ece07b8b4
Create Date: 2022-08-25 23:38:08.654156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0a9b048386'
down_revision = 'e69ece07b8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministry_approval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.drop_column('ministry_approval')

    # ### end Alembic commands ###
