"""empty message

Revision ID: c15189bf80e6
Revises: cb56e8d4f386
Create Date: 2022-08-25 16:11:58.335865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15189bf80e6'
down_revision = 'cb56e8d4f386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projectname', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infrastructure', schema=None) as batch_op:
        batch_op.drop_column('projectname')

    # ### end Alembic commands ###
