"""empty message

Revision ID: cb56e8d4f386
Revises: 99c2e58e6c1f
Create Date: 2022-08-25 16:03:24.708974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb56e8d4f386'
down_revision = '99c2e58e6c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('serialnumber', sa.Integer(), nullable=False),
    sa.Column('state_or_ut', sa.String(), nullable=False),
    sa.Column('typeofgrantee', sa.String(), nullable=False),
    sa.Column('DateofSanction', sa.DateTime(), nullable=True),
    sa.Column('Amountsanctioned', sa.Integer(), nullable=True),
    sa.Column('Amountreleased', sa.Integer(), nullable=True),
    sa.Column('percentofworkcompleted', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('serialnumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
