"""empty message

Revision ID: cd2b0434a471
Revises: bd0a9b048386
Create Date: 2022-08-26 05:00:29.764833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2b0434a471'
down_revision = 'bd0a9b048386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_2', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
