"""empty message

Revision ID: d92dc3e9c250
Revises: 5c8d7a955be2
Create Date: 2022-08-25 16:29:13.778087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92dc3e9c250'
down_revision = '5c8d7a955be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('serialnumber', sa.Integer(), nullable=False),
    sa.Column('state_or_ut', sa.String(), nullable=False),
    sa.Column('MPH', sa.Integer(), nullable=False),
    sa.Column('Athletic_track', sa.Integer(), nullable=False),
    sa.Column('Football_field', sa.Integer(), nullable=False),
    sa.Column('Hockey_field', sa.Integer(), nullable=False),
    sa.Column('swimming_pool', sa.Integer(), nullable=False),
    sa.Column('others', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('serialnumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
